name: Docker build

on:
  workflow_dispatch 
# you can trigger on anything you want

jobs:
  build:
   runs-on: ubuntu-latest
  
   steps:
     - uses: actions/checkout@v2
     - name: Build Docker image 
       run: docker build -t app .
     - name: Run tests inside the container
       run: docker images 
     -
       name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Tag image
       run: docker tag app:latest ${{ secrets.DOCKERHUB_USERNAME }}/python:app
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.SECRET_KEY }}
         aws-region: ap-southeast-1
     - name: Push image 
       run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/python:app
     - name: deploy to ec2
       env:
           PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
           HOSTNAME: ${{ secrets.HOSTNAME }}
           USER_NAME: ${{ secrets.USER_NAME }}
       run: |
         echo ${PRIVATE_KEY} > private_key && chmod 644 private_key
         ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
         sudo su - 
         docker login
         docker pull tuhao910/python:app
         docker run tuhao910/python:app
     - name: terraform 
       run: terraform init
     - name: terraform plan 
       run: terraform plan 
     - name: terrafarom apply
       run: terraform apply -auto-approve

            
